fn main() {
  let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by Cargo");
  let icons_dir = std::path::Path::new(&manifest_dir)
    .join("icons")
    .to_string_lossy()
    .replace('\\', "/");

  println!("cargo:rustc-env=FLUENTUI_ICONS_DIR={icons_dir}");

  // Re-run this build script whenever an icon is added or removed.
  println!("cargo:rerun-if-changed=icons");

  // --- icon data for MCP binary ---
  let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
  generate_icons_data(&manifest_dir, &out_dir);
}

fn generate_icons_data(manifest_dir: &str, out_dir: &str) {
  let icons_dir = std::path::Path::new(manifest_dir).join("icons");
  let dest = std::path::Path::new(out_dir).join("icons_data.rs");

  let mut entries: Vec<(String, String, String, &'static str)> = Vec::new();

  if let Ok(rd) = std::fs::read_dir(&icons_dir) {
    for entry in rd.flatten() {
      let path = entry.path();
      if path.extension().and_then(|e| e.to_str()) != Some("svg") {
        continue;
      }
      if let (Some(filename), Some(stem)) = (
        path.file_name().and_then(|n| n.to_str()),
        path.file_stem().and_then(|s| s.to_str()),
      ) {
        let fn_name = build_to_snake_case(stem);
        let variant = build_variant_of(stem);
        let base_name = build_base_name_of(stem).to_owned();
        entries.push((filename.to_owned(), fn_name, base_name, variant));
      }
    }
  }

  entries.sort_unstable_by(|a, b| a.0.cmp(&b.0));

  let mut src = String::with_capacity(entries.len() * 120 + 512);
  src.push_str("// Auto-generated by build.rs — do not edit.\n");
  src.push_str("pub struct McpIconEntry {\n");
  src.push_str("    pub filename: &'static str,\n");
  src.push_str("    pub fn_name:  &'static str,\n");
  src.push_str("    pub base_name: &'static str,\n");
  src.push_str("    pub variant:  &'static str,\n");
  src.push_str("}\n\n");
  src.push_str(&format!("pub static MCP_ICON_COUNT: usize = {};\n\n", entries.len()));
  src.push_str("pub static MCP_ALL_ICONS: &[McpIconEntry] = &[\n");
  for (filename, fn_name, base_name, variant) in &entries {
    src.push_str(&format!(
      "    McpIconEntry {{ filename: {:?}, fn_name: {:?}, base_name: {:?}, variant: {:?} }},\n",
      filename, fn_name, base_name, variant
    ));
  }
  src.push_str("];\n");

  std::fs::write(dest, src).expect("failed to write icons_data.rs");
}

/// Mirrors the `to_snake_case` logic from `src/lib.rs` for use in build.rs.
fn build_to_snake_case(s: &str) -> String {
  let chars: Vec<char> = s.chars().collect();
  let len = chars.len();
  let mut out = String::with_capacity(len + 8);

  for i in 0..len {
    let ch = chars[i];

    if ch == '_' {
      if !out.ends_with('_') {
        out.push('_');
      }
      continue;
    }

    if ch.is_ascii_uppercase() {
      let prev_lower_or_digit =
        i > 0 && chars[i - 1] != '_' && (chars[i - 1].is_ascii_lowercase() || chars[i - 1].is_ascii_digit());

      let prev_upper_next_lower =
        i > 0 && chars[i - 1].is_ascii_uppercase() && chars.get(i + 1).map(|c| c.is_ascii_lowercase()).unwrap_or(false);

      if i > 0 && !out.ends_with('_') && (prev_lower_or_digit || prev_upper_next_lower) {
        out.push('_');
      }
      out.push(ch.to_ascii_lowercase());
    } else {
      out.push(ch);
    }
  }

  if out.is_empty() { "_".to_owned() } else { out }
}

fn build_variant_of(stem: &str) -> &'static str {
  if stem.ends_with("Filled") {
    "Filled"
  } else if stem.ends_with("Color") {
    "Color"
  } else if stem.ends_with("Regular") {
    "Regular"
  } else if stem.ends_with("Light") {
    "Light"
  } else {
    ""
  }
}

fn build_base_name_of(stem: &str) -> &str {
  for suffix in &["Filled", "Color", "Regular", "Light"] {
    if let Some(base) = stem.strip_suffix(suffix) {
      return base;
    }
  }
  stem
}
